#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

#export CELERY_BROKER_URL="${REDIS_URL}"
#export DATABASE_URL="sqlite:///data/db.sqlite3"
export DATABASE_NAME="/data/db.sqlite3"
#export PYTHONPATH="/app/grodt_prj"

exec "$@"
