#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

#while true; do sleep 1; done

INIT_FN="/data/.initialized"

if [[ ! -f "${INIT_FN}" ]];
then
  python3 manage.py collectstatic --noinput

  python3 manage.py makemigrations
  python3 manage.py migrate
  python3 manage.py load_initial_data

  touch "${INIT_FN}"
  echo "Django initialized"
fi

python3 manage.py runserver 0.0.0.0:8000
